-- Service-only integration storage. Tokens never enter portal state, backups or browser responses.
create table portal_private.sportadmin_connections (
  team_id text primary key references portal_private.teams(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  lease uuid,
  lease_until timestamptz,
  updated_at timestamptz not null default now()
);
alter table portal_private.sportadmin_connections enable row level security;
revoke all on portal_private.sportadmin_connections from public, anon, authenticated;
grant select, insert, update, delete on portal_private.sportadmin_connections to service_role;
create or replace function public.portal_sportadmin(p_op text, p_args jsonb default '{}')
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare c portal_private.sportadmin_connections; t portal_private.teams; result jsonb;
begin
  if p_op = 'list' then
    return coalesce((select jsonb_agg(jsonb_build_object('id',x.team_id,'slug',y.slug))
      from portal_private.sportadmin_connections x join portal_private.teams y on y.id=x.team_id
      where x.data ? 'session'),'[]'::jsonb);
  elsif p_op = 'read' then
    return (select data from portal_private.sportadmin_connections where team_id=p_args->>'team_id');
  elsif p_op = 'acquire' then
    insert into portal_private.sportadmin_connections(team_id) values(p_args->>'team_id') on conflict do nothing;
    update portal_private.sportadmin_connections set lease=gen_random_uuid(),lease_until=now()+interval '5 minutes'
      where team_id=p_args->>'team_id' and (lease_until is null or lease_until < now()) returning * into c;
    if not found then return null; end if;
    return jsonb_build_object('lease',c.lease,'data',c.data);
  elsif p_op in ('save','finish','release') then
    select * into c from portal_private.sportadmin_connections where team_id=p_args->>'team_id' for update;
    if not found or c.lease is distinct from (p_args->>'lease')::uuid or c.lease_until < now() then
      raise exception 'CONNECTION_BUSY' using errcode='40001';
    end if;
    if p_op = 'finish' and p_args ? 'state' then
      -- Commit the state and integration mappings atomically; no notification jobs are generated by a read sync.
      result := public.portal_backend('commit',jsonb_build_object('team_id',c.team_id,
        'expected_version',p_args->'expected_version','state',p_args->'state','jobs','[]'::jsonb));
    end if;
    if p_op <> 'release' then
      if jsonb_typeof(p_args->'data') is distinct from 'object' or octet_length((p_args->'data')::text)>4000000 then
        raise exception 'INVALID_CONNECTION' using errcode='22023';
      end if;
      update portal_private.sportadmin_connections set data=p_args->'data',updated_at=now() where team_id=c.team_id;
    end if;
    if p_op in ('finish','release') then
      update portal_private.sportadmin_connections set lease=null,lease_until=null where team_id=c.team_id;
    end if;
    return coalesce(result,'{}'::jsonb);
  end if;
  raise exception 'UNKNOWN_OPERATION' using errcode='22023';
end;
$$;
revoke all on function public.portal_sportadmin(text,jsonb) from public, anon, authenticated;
grant execute on function public.portal_sportadmin(text,jsonb) to service_role;
